"""Remove property type category

Revision ID: 0f2830a194d8
Revises: c5f67bff770e
Create Date: 2021-12-07 15:31:57.789695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2830a194d8'
down_revision = 'c5f67bff770e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.drop_constraint('property_types_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('property_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('property_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('property_types_category_id_fkey', 'property_categories', ['category_id'], ['id'])
        batch_op.drop_column('category')
    # ### end Alembic commands ###
