"""Add linkedin fields to user

Revision ID: 8e22c1e7c460
Revises: 0f2830a194d8
Create Date: 2021-12-09 16:40:59.323614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e22c1e7c460'
down_revision = '0f2830a194d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_username', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('linkedin_password', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('linkedin_password')
        batch_op.drop_column('linkedin_username')

    # ### end Alembic commands ###
