"""Add captical to country

Revision ID: 97f52d5800fd
Revises: 8e22c1e7c460
Create Date: 2021-12-17 17:41:20.361678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f52d5800fd'
down_revision = '8e22c1e7c460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capital_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('capital_longitude', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('capital_latitude', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_column('capital_latitude')
        batch_op.drop_column('capital_longitude')
        batch_op.drop_column('capital_name')

    # ### end Alembic commands ###
